language: scala
scala:
  - 2.11.12
jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'

script:
  - pwd
  - ls -a
  - cd TripPlanning_V1

notifications:
  email:
    - Zhou.yiy@husky.neu.edu
